version: 2

jobs:
  build:
      docker:
        - image: circleci/golang:1.15
      working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
      steps:
        - checkout
        - run: go get -v -t -d ./...
        - run: go test -v ./...
    
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4c:57:23:da:7b:fc:79:27:14:83:44:7a:49:c6:5a:f5"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./deploy/script.sh deploy/osquery-server"

workflows:
   version: 2
   build-and-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master
