version: 2

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "82:8d:99:87:ff:c2:11:5c:f3:cb:ab:ae:28:8f:35:fa"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "ls -la"