version: 2

jobs:
  build:
      docker:
        - image: circleci/golang:1.15
      working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
      steps:
        - checkout
        - run: go get -v -t -d ./...
        - run: go test -v ./...
    
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "82:8d:99:87:ff:c2:11:5c:f3:cb:ab:ae:28:8f:35:fa"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "ls -la"

workflows:
   version: 2
   build-and-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only deploy once build job has completed
           filters:
             branches:
               only: master # only deploy on the master branch
